---

- import_tasks: check_for_sap_instances.yml

- import_tasks: ev_user.yml
  when:
    - sap_hana_deployment_hana_userid == ''
    - not sap_hana_deployment_apply_license
    - not sap_hana_deployment_skip

- import_tasks: ev_group.yml
  when:
    - sap_hana_deployment_hana_groupid == ''
    - not sap_hana_deployment_apply_license
    - not sap_hana_deployment_skip

- import_tasks: password_facts.yml
  when:
    - sap_hana_deployment_use_master_password == 'y'
    - not sap_hana_deployment_skip

- import_tasks: hana_deploy.yml
  when:
    - not sap_hana_deployment_apply_license
    - not sap_hana_deployment_skip

- import_tasks: license.yml
  when: sap_hana_deployment_apply_license
